#NAME: Eugene Choi
#EMAIL: echoi2@g.ucla.edu
#ID: 905368197

clean:
	@rm -f *tar.gz
dist:
	@tar -czvf lab4a-905368197.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README
