#NAME: Eugene Choi
#EMAIL: echoi2@g.ucla.edu
#ID: 905368197

CFLAGS = -g -Wall -Wextra
CC = gcc

default:
	@$(CC) $(CFLAGS) lab3a.c -o lab3a 
clean:
	@rm -f lab3a *.tar.gz
dist:
	@tar -czvf lab3a-905368197.tar.gz lab3a.c README Makefile ext2_fs.h